version: '3.1'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: real_estate
    ports:
      - 5432:5432
    volumes:
      - ../upwork_db:/var/lib/postgresql/data
  # mongo:
  #   image: mongo
  #   restart: always
  #   ports:
  #     - "27017:27017"

  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example
  #   volumes:
  #     - ../db-data/mongo/:/data/db

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #     ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
